package crystalscriptcompiler;

/* The following code was generated by JFlex 1.4.3 on 6/2/13 8:42 AM */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 1998-2009  Gerwin Klein <lsf@jflex.de>                    *
 * All rights reserved.                                                    *
 *                                                                         *
 * This program is free software; you can redistribute it and/or modify    *
 * it under the terms of the GNU General Public License. See the file      *
 * COPYRIGHT for more information.                                         *
 *                                                                         *
 * This program is distributed in the hope that it will be useful,         *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of          *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
 * GNU General Public License for more details.                            *
 *                                                                         *
 * You should have received a copy of the GNU General Public License along *
 * with this program; if not, write to the Free Software Foundation, Inc., *
 * 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA                 *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* Java 1.2 language lexer specification */

/* Use together with unicode.flex for Unicode preprocesssing */
/* and java12.cup for a Java 1.2 parser                      */

/* Note that this lexer specification is not tuned for speed.
   It is in fact quite slow on integer and floating point literals, 
   because the input is read twice and the methods used to parse
   the numbers are not very fast. 
   For a production quality application (e.g. a Java compiler) 
   this could be optimized */


import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/2/13 8:42 AM from the specification file
 * <tt>C:/Users/User/Documents/GitHub/CrystalScriptCompiler/generated_code/crystalscript.flex</tt>
 */
public class Scanner implements CrystalSymbol, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\0\1\3\1\1\16\7\4\0\1\3\1\62"+
    "\1\14\1\0\1\6\1\72\1\66\1\16\1\47\1\50\1\5\1\70"+
    "\1\56\1\13\1\11\1\4\12\10\1\65\1\55\1\61\1\57\1\60"+
    "\1\64\1\0\4\6\1\12\25\6\1\51\1\15\1\52\1\71\1\6"+
    "\1\0\1\24\1\22\1\26\1\37\1\32\1\23\1\45\1\34\1\35"+
    "\1\44\1\33\1\31\1\41\1\17\1\30\1\42\1\6\1\20\1\25"+
    "\1\21\1\36\1\46\1\43\1\40\1\27\1\6\1\53\1\67\1\54"+
    "\1\63\41\7\2\0\4\6\4\0\1\6\2\0\1\7\7\0\1\6"+
    "\4\0\1\6\5\0\27\6\1\0\37\6\1\0\u01ca\6\4\0\14\6"+
    "\16\0\5\6\7\0\1\6\1\0\1\6\21\0\160\7\5\6\1\0"+
    "\2\6\2\0\4\6\10\0\1\6\1\0\3\6\1\0\1\6\1\0"+
    "\24\6\1\0\123\6\1\0\213\6\1\0\5\7\2\0\236\6\11\0"+
    "\46\6\2\0\1\6\7\0\47\6\11\0\55\7\1\0\1\7\1\0"+
    "\2\7\1\0\2\7\1\0\1\7\10\0\33\6\5\0\3\6\15\0"+
    "\4\7\7\0\1\6\4\0\13\7\5\0\53\6\37\7\4\0\2\6"+
    "\1\7\143\6\1\0\1\6\10\7\1\0\6\7\2\6\2\7\1\0"+
    "\4\7\2\6\12\7\3\6\2\0\1\6\17\0\1\7\1\6\1\7"+
    "\36\6\33\7\2\0\131\6\13\7\1\6\16\0\12\7\41\6\11\7"+
    "\2\6\4\0\1\6\5\0\26\6\4\7\1\6\11\7\1\6\3\7"+
    "\1\6\5\7\22\0\31\6\3\7\244\0\4\7\66\6\3\7\1\6"+
    "\22\7\1\6\7\7\12\6\2\7\2\0\12\7\1\0\7\6\1\0"+
    "\7\6\1\0\3\7\1\0\10\6\2\0\2\6\2\0\26\6\1\0"+
    "\7\6\1\0\1\6\3\0\4\6\2\0\1\7\1\6\7\7\2\0"+
    "\2\7\2\0\3\7\1\6\10\0\1\7\4\0\2\6\1\0\3\6"+
    "\2\7\2\0\12\7\4\6\7\0\1\6\5\0\3\7\1\0\6\6"+
    "\4\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0\2\6"+
    "\1\0\2\6\2\0\1\7\1\0\5\7\4\0\2\7\2\0\3\7"+
    "\3\0\1\7\7\0\4\6\1\0\1\6\7\0\14\7\3\6\1\7"+
    "\13\0\3\7\1\0\11\6\1\0\3\6\1\0\26\6\1\0\7\6"+
    "\1\0\2\6\1\0\5\6\2\0\1\7\1\6\10\7\1\0\3\7"+
    "\1\0\3\7\2\0\1\6\17\0\2\6\2\7\2\0\12\7\1\0"+
    "\1\6\17\0\3\7\1\0\10\6\2\0\2\6\2\0\26\6\1\0"+
    "\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6\7\7\2\0"+
    "\2\7\2\0\3\7\10\0\2\7\4\0\2\6\1\0\3\6\2\7"+
    "\2\0\12\7\1\0\1\6\20\0\1\7\1\6\1\0\6\6\3\0"+
    "\3\6\1\0\4\6\3\0\2\6\1\0\1\6\1\0\2\6\3\0"+
    "\2\6\3\0\3\6\3\0\14\6\4\0\5\7\3\0\3\7\1\0"+
    "\4\7\2\0\1\6\6\0\1\7\16\0\12\7\11\0\1\6\7\0"+
    "\3\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0"+
    "\5\6\3\0\1\6\7\7\1\0\3\7\1\0\4\7\7\0\2\7"+
    "\1\0\2\6\6\0\2\6\2\7\2\0\12\7\22\0\2\7\1\0"+
    "\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6\2\0"+
    "\1\7\1\6\7\7\1\0\3\7\1\0\4\7\7\0\2\7\7\0"+
    "\1\6\1\0\2\6\2\7\2\0\12\7\1\0\2\6\17\0\2\7"+
    "\1\0\10\6\1\0\3\6\1\0\51\6\2\0\1\6\7\7\1\0"+
    "\3\7\1\0\4\7\1\6\10\0\1\7\10\0\2\6\2\7\2\0"+
    "\12\7\12\0\6\6\2\0\2\7\1\0\22\6\3\0\30\6\1\0"+
    "\11\6\1\0\1\6\2\0\7\6\3\0\1\7\4\0\6\7\1\0"+
    "\1\7\1\0\10\7\22\0\2\7\15\0\60\6\1\7\2\6\7\7"+
    "\4\0\10\6\10\7\1\0\12\7\47\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\2\0\1\6\6\0\4\6\1\0\7\6\1\0"+
    "\3\6\1\0\1\6\1\0\1\6\2\0\2\6\1\0\4\6\1\7"+
    "\2\6\6\7\1\0\2\7\1\6\2\0\5\6\1\0\1\6\1\0"+
    "\6\7\2\0\12\7\2\0\2\6\42\0\1\6\27\0\2\7\6\0"+
    "\12\7\13\0\1\7\1\0\1\7\1\0\1\7\4\0\2\7\10\6"+
    "\1\0\44\6\4\0\24\7\1\0\2\7\5\6\13\7\1\0\44\7"+
    "\11\0\1\7\71\0\53\6\24\7\1\6\12\7\6\0\6\6\4\7"+
    "\4\6\3\7\1\6\3\7\2\6\7\7\3\6\4\7\15\6\14\7"+
    "\1\6\17\7\2\0\46\6\12\0\53\6\1\0\1\6\3\0\u0149\6"+
    "\1\0\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0\51\6"+
    "\1\0\4\6\2\0\41\6\1\0\4\6\2\0\7\6\1\0\1\6"+
    "\1\0\4\6\2\0\17\6\1\0\71\6\1\0\4\6\2\0\103\6"+
    "\2\0\3\7\40\0\20\6\20\0\125\6\14\0\u026c\6\2\0\21\6"+
    "\1\0\32\6\5\0\113\6\3\0\3\6\17\0\15\6\1\0\4\6"+
    "\3\7\13\0\22\6\3\7\13\0\22\6\2\7\14\0\15\6\1\0"+
    "\3\6\1\0\2\7\14\0\64\6\40\7\3\0\1\6\3\0\2\6"+
    "\1\7\2\0\12\7\41\0\3\7\2\0\12\7\6\0\130\6\10\0"+
    "\51\6\1\7\1\6\5\0\106\6\12\0\35\6\3\0\14\7\4\0"+
    "\14\7\12\0\12\7\36\6\2\0\5\6\13\0\54\6\4\0\21\7"+
    "\7\6\2\7\6\0\12\7\46\0\27\6\5\7\4\0\65\6\12\7"+
    "\1\0\35\7\2\0\13\7\6\0\12\7\15\0\1\6\130\0\5\7"+
    "\57\6\21\7\7\6\4\0\12\7\21\0\11\7\14\0\3\7\36\6"+
    "\12\7\3\0\2\6\12\7\6\0\46\6\16\7\14\0\44\6\24\7"+
    "\10\0\12\7\3\0\3\6\12\7\44\6\122\0\3\7\1\0\25\7"+
    "\4\6\1\7\4\6\1\7\15\0\300\6\47\7\25\0\4\7\u0116\6"+
    "\2\0\6\6\2\0\46\6\2\0\6\6\2\0\10\6\1\0\1\6"+
    "\1\0\1\6\1\0\1\6\1\0\37\6\2\0\65\6\1\0\7\6"+
    "\1\0\1\6\3\0\3\6\1\0\7\6\3\0\4\6\2\0\6\6"+
    "\4\0\15\6\5\0\3\6\1\0\7\6\16\0\5\7\32\0\5\7"+
    "\20\0\2\6\23\0\1\6\13\0\5\7\5\0\6\7\1\0\1\6"+
    "\15\0\1\6\20\0\15\6\3\0\32\6\26\0\15\7\4\0\1\7"+
    "\3\0\14\7\21\0\1\6\4\0\1\6\2\0\12\6\1\0\1\6"+
    "\3\0\5\6\6\0\1\6\1\0\1\6\1\0\1\6\1\0\4\6"+
    "\1\0\13\6\2\0\4\6\5\0\5\6\4\0\1\6\21\0\51\6"+
    "\u0a77\0\57\6\1\0\57\6\1\0\205\6\6\0\4\6\3\7\16\0"+
    "\46\6\12\0\66\6\11\0\1\6\17\0\1\7\27\6\11\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\40\7\57\0\1\6\u01d5\0\3\6"+
    "\31\0\11\6\6\7\1\0\5\6\2\0\5\6\4\0\126\6\2\0"+
    "\2\7\2\0\3\6\1\0\132\6\1\0\4\6\5\0\51\6\3\0"+
    "\136\6\21\0\33\6\65\0\20\6\u0200\0\u19b6\6\112\0\u51cc\6\64\0"+
    "\u048d\6\103\0\56\6\2\0\u010d\6\3\0\20\6\12\7\2\6\24\0"+
    "\57\6\1\7\14\0\2\7\1\0\31\6\10\0\120\6\2\7\45\0"+
    "\11\6\2\0\147\6\2\0\4\6\1\0\2\6\16\0\12\6\120\0"+
    "\10\6\1\7\3\6\1\7\4\6\1\7\27\6\5\7\20\0\1\6"+
    "\7\0\64\6\14\0\2\7\62\6\21\7\13\0\12\7\6\0\22\7"+
    "\6\6\3\0\1\6\4\0\12\7\34\6\10\7\2\0\27\6\15\7"+
    "\14\0\35\6\3\0\4\7\57\6\16\7\16\0\1\6\12\7\46\0"+
    "\51\6\16\7\11\0\3\6\1\7\10\6\2\7\2\0\12\7\6\0"+
    "\27\6\3\0\1\6\1\7\4\0\60\6\1\7\1\6\3\7\2\6"+
    "\2\7\5\6\2\7\1\6\1\7\1\6\30\0\3\6\43\0\6\6"+
    "\2\0\6\6\2\0\6\6\11\0\7\6\1\0\7\6\221\0\43\6"+
    "\10\7\1\0\2\7\2\0\12\7\6\0\u2ba4\6\14\0\27\6\4\0"+
    "\61\6\u2104\0\u012e\6\2\0\76\6\2\0\152\6\46\0\7\6\14\0"+
    "\5\6\5\0\1\6\1\7\12\6\1\0\15\6\1\0\5\6\1\0"+
    "\1\6\1\0\2\6\1\0\2\6\1\0\154\6\41\0\u016b\6\22\0"+
    "\100\6\2\0\66\6\50\0\15\6\3\0\20\7\20\0\7\7\14\0"+
    "\2\6\30\0\3\6\31\0\1\6\6\0\5\6\1\0\207\6\2\0"+
    "\1\7\4\0\1\6\13\0\12\7\7\0\32\6\4\0\1\6\1\0"+
    "\32\6\13\0\131\6\3\0\6\6\2\0\6\6\2\0\6\6\2\0"+
    "\3\6\3\0\2\6\3\0\2\6\22\0\3\7\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\20\5\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\2\1\37\1\1\1\2\1\0\1\40\1\41\1\6"+
    "\1\0\1\42\1\43\15\5\1\44\12\5\1\45\1\46"+
    "\2\5\1\47\6\5\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\63\1\64"+
    "\1\65\1\66\1\36\1\0\1\6\1\0\1\67\3\5"+
    "\1\70\7\5\1\71\22\5\1\72\5\5\1\73\1\74"+
    "\1\75\1\76\1\0\1\77\2\5\1\100\1\5\1\101"+
    "\2\5\1\102\11\5\1\103\3\5\1\104\2\5\1\105"+
    "\6\5\1\106\2\5\1\107\2\5\1\110\1\111\1\5"+
    "\1\112\1\5\1\113\3\5\1\114\1\5\1\115\1\5"+
    "\1\116\12\5\1\117\1\120\1\121\3\5\1\122\1\123"+
    "\1\124\1\5\1\125\2\5\1\126\5\5\1\127\1\130"+
    "\1\131\2\5\1\132\3\5\1\133\1\5\1\134\1\135"+
    "\1\136\4\5\1\137\1\5\1\140\1\141\1\142";

  private static int [] zzUnpackAction() {
    int [] result = new int[260];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\166\0\354\0\u0127\0\u0162"+
    "\0\u019d\0\u01d8\0\u0213\0\166\0\u024e\0\u0289\0\u02c4\0\u02ff"+
    "\0\u033a\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7"+
    "\0\u0512\0\u054d\0\u0588\0\u05c3\0\166\0\166\0\166\0\166"+
    "\0\166\0\166\0\166\0\166\0\u05fe\0\u0639\0\u0674\0\u06af"+
    "\0\166\0\166\0\166\0\u06ea\0\u0725\0\u0760\0\u079b\0\u07d6"+
    "\0\u0811\0\u084c\0\166\0\u0887\0\u08c2\0\u08fd\0\166\0\166"+
    "\0\u0938\0\u0973\0\166\0\166\0\u09ae\0\u09e9\0\u0a24\0\u0a5f"+
    "\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37"+
    "\0\u0c72\0\u0162\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4"+
    "\0\u0e0f\0\u0e4a\0\u0e85\0\u0ec0\0\u0162\0\u0efb\0\u0f36\0\u0f71"+
    "\0\u0162\0\u0fac\0\u0fe7\0\u1022\0\u105d\0\u1098\0\u10d3\0\166"+
    "\0\166\0\u110e\0\166\0\u1149\0\166\0\166\0\166\0\166"+
    "\0\166\0\166\0\166\0\166\0\166\0\166\0\u1184\0\u11bf"+
    "\0\u11fa\0\u11fa\0\u0162\0\u1235\0\u1270\0\u12ab\0\u0162\0\u12e6"+
    "\0\u1321\0\u135c\0\u1397\0\u13d2\0\u140d\0\u1448\0\u0162\0\u1483"+
    "\0\u14be\0\u14f9\0\u1534\0\u156f\0\u15aa\0\u15e5\0\u1620\0\u165b"+
    "\0\u1696\0\u16d1\0\u170c\0\u1747\0\u1782\0\u17bd\0\u17f8\0\u1833"+
    "\0\u186e\0\u18a9\0\u18e4\0\u191f\0\u195a\0\u1995\0\u19d0\0\u0162"+
    "\0\166\0\u1a0b\0\166\0\u1a46\0\u0162\0\u1a81\0\u1abc\0\u0162"+
    "\0\u1af7\0\u0162\0\u1b32\0\u1b6d\0\u0162\0\u1ba8\0\u1be3\0\u1c1e"+
    "\0\u1c59\0\u1c94\0\u1ccf\0\u1d0a\0\u1d45\0\u1d80\0\u0162\0\u1dbb"+
    "\0\u1df6\0\u1e31\0\u0162\0\u1e6c\0\u1ea7\0\u0162\0\u1ee2\0\u1f1d"+
    "\0\u1f58\0\u1f93\0\u1fce\0\u2009\0\u0162\0\u2044\0\u207f\0\166"+
    "\0\u20ba\0\u20f5\0\u0162\0\u0162\0\u2130\0\u0162\0\u216b\0\u0162"+
    "\0\u21a6\0\u21e1\0\u221c\0\u0162\0\u2257\0\u0162\0\u2292\0\u0162"+
    "\0\u22cd\0\u2308\0\u2343\0\u237e\0\u23b9\0\u23f4\0\u242f\0\u246a"+
    "\0\u24a5\0\u24e0\0\u0162\0\u0162\0\u0162\0\u251b\0\u2556\0\u2591"+
    "\0\u0162\0\u0162\0\u0162\0\u25cc\0\u0162\0\u2607\0\u2642\0\u0162"+
    "\0\u267d\0\u26b8\0\u26f3\0\u272e\0\u2769\0\u0162\0\u0162\0\u0162"+
    "\0\u27a4\0\u27df\0\u0162\0\u281a\0\u2855\0\u2890\0\u0162\0\u28cb"+
    "\0\u0162\0\u0162\0\u0162\0\u2906\0\u2941\0\u297c\0\u29b7\0\u0162"+
    "\0\u29f2\0\u0162\0\u0162\0\u0162";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[260];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\12\1\10\1\13\1\14\2\3\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\10\1\25\1\10"+
    "\1\26\2\10\1\27\1\30\1\31\2\10\1\32\1\33"+
    "\2\10\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\2\62"+
    "\11\61\1\63\1\64\55\61\75\0\1\5\74\0\1\65"+
    "\1\66\51\0\1\67\72\0\1\70\21\0\3\10\1\0"+
    "\1\10\4\0\30\10\34\0\1\11\1\71\1\72\17\0"+
    "\1\72\50\0\1\71\75\0\1\73\43\0\1\74\21\0"+
    "\3\10\1\0\1\10\4\0\13\10\1\75\3\10\1\76"+
    "\10\10\32\0\3\10\1\0\1\10\4\0\13\10\1\77"+
    "\14\10\32\0\3\10\1\0\1\10\4\0\1\10\1\100"+
    "\13\10\1\101\12\10\32\0\3\10\1\0\1\10\4\0"+
    "\1\10\1\102\7\10\1\103\16\10\32\0\3\10\1\0"+
    "\1\10\4\0\1\10\1\104\3\10\1\105\3\10\1\106"+
    "\4\10\1\107\11\10\32\0\3\10\1\0\1\10\4\0"+
    "\1\10\1\110\1\10\1\111\2\10\1\112\21\10\32\0"+
    "\3\10\1\0\1\10\4\0\2\10\1\113\14\10\1\114"+
    "\4\10\1\115\3\10\32\0\3\10\1\0\1\10\4\0"+
    "\5\10\1\116\3\10\1\117\1\120\15\10\32\0\3\10"+
    "\1\0\1\10\4\0\3\10\1\121\24\10\32\0\3\10"+
    "\1\0\1\10\4\0\12\10\1\122\6\10\1\123\6\10"+
    "\32\0\3\10\1\0\1\10\4\0\1\124\3\10\1\125"+
    "\1\10\1\126\13\10\1\127\5\10\32\0\3\10\1\0"+
    "\1\10\4\0\1\130\27\10\32\0\3\10\1\0\1\10"+
    "\4\0\11\10\1\131\1\10\1\132\14\10\32\0\3\10"+
    "\1\0\1\10\4\0\1\10\1\133\3\10\1\134\11\10"+
    "\1\135\10\10\32\0\3\10\1\0\1\10\4\0\15\10"+
    "\1\136\12\10\32\0\3\10\1\0\1\10\4\0\5\10"+
    "\1\137\22\10\103\0\1\140\72\0\1\141\1\142\71\0"+
    "\1\143\1\0\1\144\70\0\1\145\72\0\1\146\6\0"+
    "\1\147\63\0\1\150\7\0\1\151\62\0\1\152\10\0"+
    "\1\153\61\0\1\154\72\0\1\155\13\0\1\61\2\0"+
    "\11\61\2\0\55\61\1\0\2\62\70\0\2\156\1\0"+
    "\11\156\10\157\47\156\1\65\1\4\1\5\70\65\5\66"+
    "\1\160\65\66\10\0\1\71\1\0\1\72\17\0\1\72"+
    "\50\0\1\161\2\0\1\162\54\0\1\162\10\0\3\10"+
    "\1\0\1\10\4\0\24\10\1\163\3\10\32\0\3\10"+
    "\1\0\1\10\4\0\12\10\1\164\7\10\1\165\5\10"+
    "\32\0\3\10\1\0\1\10\4\0\2\10\1\166\25\10"+
    "\32\0\3\10\1\0\1\10\4\0\10\10\1\167\6\10"+
    "\1\170\10\10\32\0\3\10\1\0\1\10\4\0\1\10"+
    "\1\171\14\10\1\172\11\10\32\0\3\10\1\0\1\10"+
    "\4\0\13\10\1\173\14\10\32\0\3\10\1\0\1\10"+
    "\4\0\11\10\1\174\16\10\32\0\3\10\1\0\1\10"+
    "\4\0\11\10\1\175\16\10\32\0\3\10\1\0\1\10"+
    "\4\0\12\10\1\176\15\10\32\0\3\10\1\0\1\10"+
    "\4\0\1\10\1\177\26\10\32\0\3\10\1\0\1\10"+
    "\4\0\1\200\27\10\32\0\3\10\1\0\1\10\4\0"+
    "\1\10\1\201\26\10\32\0\3\10\1\0\1\10\4\0"+
    "\6\10\1\202\21\10\32\0\3\10\1\0\1\10\4\0"+
    "\1\10\1\203\3\10\1\204\22\10\32\0\3\10\1\0"+
    "\1\10\4\0\23\10\1\205\4\10\32\0\3\10\1\0"+
    "\1\10\4\0\16\10\1\206\11\10\32\0\3\10\1\0"+
    "\1\10\4\0\2\10\1\207\3\10\1\210\21\10\32\0"+
    "\3\10\1\0\1\10\4\0\1\211\27\10\32\0\3\10"+
    "\1\0\1\10\4\0\5\10\1\212\22\10\32\0\3\10"+
    "\1\0\1\10\4\0\25\10\1\213\2\10\32\0\3\10"+
    "\1\0\1\10\4\0\6\10\1\214\21\10\32\0\3\10"+
    "\1\0\1\10\4\0\2\10\1\215\25\10\32\0\3\10"+
    "\1\0\1\10\4\0\2\10\1\216\25\10\32\0\3\10"+
    "\1\0\1\10\4\0\1\217\27\10\32\0\3\10\1\0"+
    "\1\10\4\0\23\10\1\220\4\10\32\0\3\10\1\0"+
    "\1\10\4\0\20\10\1\221\7\10\32\0\3\10\1\0"+
    "\1\10\4\0\4\10\1\222\23\10\32\0\3\10\1\0"+
    "\1\10\4\0\11\10\1\223\4\10\1\224\11\10\32\0"+
    "\3\10\1\0\1\10\4\0\6\10\1\225\21\10\32\0"+
    "\3\10\1\0\1\10\4\0\3\10\1\226\24\10\32\0"+
    "\3\10\1\0\1\10\4\0\16\10\1\227\11\10\32\0"+
    "\3\10\1\0\1\10\4\0\1\10\1\230\26\10\103\0"+
    "\1\231\1\232\71\0\1\233\30\0\1\234\55\0\4\66"+
    "\1\5\1\160\65\66\10\0\1\161\70\0\3\10\1\0"+
    "\1\10\4\0\12\10\1\235\15\10\32\0\3\10\1\0"+
    "\1\10\4\0\3\10\1\236\24\10\32\0\3\10\1\0"+
    "\1\10\4\0\17\10\1\237\10\10\32\0\3\10\1\0"+
    "\1\10\4\0\13\10\1\240\14\10\32\0\3\10\1\0"+
    "\1\10\4\0\11\10\1\241\16\10\32\0\3\10\1\0"+
    "\1\10\4\0\6\10\1\242\21\10\32\0\3\10\1\0"+
    "\1\10\4\0\5\10\1\243\22\10\32\0\3\10\1\0"+
    "\1\10\4\0\12\10\1\244\15\10\32\0\3\10\1\0"+
    "\1\10\4\0\22\10\1\245\5\10\32\0\3\10\1\0"+
    "\1\10\4\0\6\10\1\246\21\10\32\0\3\10\1\0"+
    "\1\10\4\0\5\10\1\247\22\10\32\0\3\10\1\0"+
    "\1\10\4\0\5\10\1\250\22\10\32\0\3\10\1\0"+
    "\1\10\4\0\2\10\1\251\25\10\32\0\3\10\1\0"+
    "\1\10\4\0\16\10\1\252\11\10\32\0\3\10\1\0"+
    "\1\10\4\0\2\10\1\253\25\10\32\0\3\10\1\0"+
    "\1\10\4\0\13\10\1\254\14\10\32\0\3\10\1\0"+
    "\1\10\4\0\2\10\1\255\25\10\32\0\3\10\1\0"+
    "\1\10\4\0\7\10\1\256\20\10\32\0\3\10\1\0"+
    "\1\10\4\0\13\10\1\257\14\10\32\0\3\10\1\0"+
    "\1\10\4\0\2\10\1\260\25\10\32\0\3\10\1\0"+
    "\1\10\4\0\6\10\1\261\21\10\32\0\3\10\1\0"+
    "\1\10\4\0\13\10\1\262\14\10\32\0\3\10\1\0"+
    "\1\10\4\0\13\10\1\263\14\10\32\0\3\10\1\0"+
    "\1\10\4\0\13\10\1\264\14\10\32\0\3\10\1\0"+
    "\1\10\4\0\13\10\1\265\14\10\32\0\3\10\1\0"+
    "\1\10\4\0\2\10\1\266\25\10\32\0\3\10\1\0"+
    "\1\10\4\0\11\10\1\267\1\270\15\10\32\0\3\10"+
    "\1\0\1\10\4\0\13\10\1\271\14\10\32\0\3\10"+
    "\1\0\1\10\4\0\5\10\1\272\22\10\32\0\3\10"+
    "\1\0\1\10\4\0\2\10\1\273\25\10\32\0\3\10"+
    "\1\0\1\10\4\0\27\10\1\274\32\0\3\10\1\0"+
    "\1\10\4\0\6\10\1\275\21\10\32\0\3\10\1\0"+
    "\1\10\4\0\12\10\1\276\15\10\32\0\3\10\1\0"+
    "\1\10\4\0\12\10\1\277\15\10\103\0\1\300\27\0"+
    "\10\157\55\0\3\10\1\0\1\10\4\0\13\10\1\301"+
    "\14\10\32\0\3\10\1\0\1\10\4\0\1\10\1\302"+
    "\26\10\32\0\3\10\1\0\1\10\4\0\24\10\1\303"+
    "\3\10\32\0\3\10\1\0\1\10\4\0\14\10\1\304"+
    "\13\10\32\0\3\10\1\0\1\10\4\0\13\10\1\305"+
    "\14\10\32\0\3\10\1\0\1\10\4\0\13\10\1\306"+
    "\14\10\32\0\3\10\1\0\1\10\4\0\12\10\1\307"+
    "\15\10\32\0\3\10\1\0\1\10\4\0\10\10\1\310"+
    "\17\10\32\0\3\10\1\0\1\10\4\0\1\10\1\311"+
    "\26\10\32\0\3\10\1\0\1\10\4\0\1\312\27\10"+
    "\32\0\3\10\1\0\1\10\4\0\16\10\1\313\11\10"+
    "\32\0\3\10\1\0\1\10\4\0\1\10\1\314\26\10"+
    "\32\0\3\10\1\0\1\10\4\0\7\10\1\315\20\10"+
    "\32\0\3\10\1\0\1\10\4\0\15\10\1\316\12\10"+
    "\32\0\3\10\1\0\1\10\4\0\16\10\1\317\11\10"+
    "\32\0\3\10\1\0\1\10\4\0\6\10\1\320\21\10"+
    "\32\0\3\10\1\0\1\10\4\0\7\10\1\321\20\10"+
    "\32\0\3\10\1\0\1\10\4\0\1\322\27\10\32\0"+
    "\3\10\1\0\1\10\4\0\1\10\1\323\26\10\32\0"+
    "\3\10\1\0\1\10\4\0\1\10\1\324\26\10\32\0"+
    "\3\10\1\0\1\10\4\0\13\10\1\325\14\10\32\0"+
    "\3\10\1\0\1\10\4\0\4\10\1\326\23\10\32\0"+
    "\3\10\1\0\1\10\4\0\17\10\1\327\10\10\32\0"+
    "\3\10\1\0\1\10\4\0\13\10\1\330\14\10\32\0"+
    "\3\10\1\0\1\10\4\0\5\10\1\331\22\10\32\0"+
    "\3\10\1\0\1\10\4\0\16\10\1\332\11\10\32\0"+
    "\3\10\1\0\1\10\4\0\13\10\1\333\14\10\32\0"+
    "\3\10\1\0\1\10\4\0\1\10\1\334\26\10\32\0"+
    "\3\10\1\0\1\10\4\0\1\335\27\10\32\0\3\10"+
    "\1\0\1\10\4\0\5\10\1\336\22\10\32\0\3\10"+
    "\1\0\1\10\4\0\12\10\1\337\15\10\32\0\3\10"+
    "\1\0\1\10\4\0\5\10\1\340\22\10\32\0\3\10"+
    "\1\0\1\10\4\0\26\10\1\341\1\10\32\0\3\10"+
    "\1\0\1\10\4\0\7\10\1\342\20\10\32\0\3\10"+
    "\1\0\1\10\4\0\15\10\1\343\12\10\32\0\3\10"+
    "\1\0\1\10\4\0\1\344\27\10\32\0\3\10\1\0"+
    "\1\10\4\0\2\10\1\345\25\10\32\0\3\10\1\0"+
    "\1\10\4\0\20\10\1\346\7\10\32\0\3\10\1\0"+
    "\1\10\4\0\4\10\1\347\23\10\32\0\3\10\1\0"+
    "\1\10\4\0\2\10\1\350\25\10\32\0\3\10\1\0"+
    "\1\10\4\0\22\10\1\351\5\10\32\0\3\10\1\0"+
    "\1\10\4\0\16\10\1\352\11\10\32\0\3\10\1\0"+
    "\1\10\4\0\12\10\1\353\15\10\32\0\3\10\1\0"+
    "\1\10\4\0\7\10\1\354\20\10\32\0\3\10\1\0"+
    "\1\10\4\0\2\10\1\355\25\10\32\0\3\10\1\0"+
    "\1\10\4\0\7\10\1\356\20\10\32\0\3\10\1\0"+
    "\1\10\4\0\1\357\27\10\32\0\3\10\1\0\1\10"+
    "\4\0\10\10\1\360\17\10\32\0\3\10\1\0\1\10"+
    "\4\0\7\10\1\361\20\10\32\0\3\10\1\0\1\10"+
    "\4\0\17\10\1\362\10\10\32\0\3\10\1\0\1\10"+
    "\4\0\6\10\1\363\21\10\32\0\3\10\1\0\1\10"+
    "\4\0\5\10\1\364\22\10\32\0\3\10\1\0\1\10"+
    "\4\0\13\10\1\365\14\10\32\0\3\10\1\0\1\10"+
    "\4\0\1\366\27\10\32\0\3\10\1\0\1\10\4\0"+
    "\2\10\1\367\25\10\32\0\3\10\1\0\1\10\4\0"+
    "\2\10\1\370\25\10\32\0\3\10\1\0\1\10\4\0"+
    "\13\10\1\371\14\10\32\0\3\10\1\0\1\10\4\0"+
    "\2\10\1\372\25\10\32\0\3\10\1\0\1\10\4\0"+
    "\13\10\1\373\14\10\32\0\3\10\1\0\1\10\4\0"+
    "\7\10\1\374\20\10\32\0\3\10\1\0\1\10\4\0"+
    "\1\375\27\10\32\0\3\10\1\0\1\10\4\0\13\10"+
    "\1\376\14\10\32\0\3\10\1\0\1\10\4\0\13\10"+
    "\1\377\14\10\32\0\3\10\1\0\1\10\4\0\13\10"+
    "\1\u0100\14\10\32\0\3\10\1\0\1\10\4\0\2\10"+
    "\1\u0101\25\10\32\0\3\10\1\0\1\10\4\0\20\10"+
    "\1\u0102\7\10\32\0\3\10\1\0\1\10\4\0\20\10"+
    "\1\u0103\7\10\32\0\3\10\1\0\1\10\4\0\6\10"+
    "\1\u0104\21\10\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10797];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\6\1\1\11\20\1\10\11"+
    "\4\1\3\11\7\1\1\11\2\1\1\0\2\11\1\1"+
    "\1\0\2\11\43\1\2\11\1\1\1\11\1\1\12\11"+
    "\1\1\1\0\1\1\1\0\46\1\1\11\1\1\1\11"+
    "\1\0\43\1\1\11\104\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[260];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  
  private Symbol symbol(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2216) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 41: 
          { return symbol(GTEQ);
          }
        case 99: break;
        case 28: 
          { return symbol(XOR);
          }
        case 100: break;
        case 19: 
          { return symbol(GT);
          }
        case 101: break;
        case 85: 
          { return symbol(OBJECT);
          }
        case 102: break;
        case 59: 
          { return symbol(VAR);
          }
        case 103: break;
        case 45: 
          { return symbol(NOTEQ);
          }
        case 104: break;
        case 9: 
          { yybegin(STRING); string.setLength(0);
          }
        case 105: break;
        case 14: 
          { return symbol(LBRACE);
          }
        case 106: break;
        case 18: 
          { return symbol(EQ);
          }
        case 107: break;
        case 34: 
          { return symbol(MINUSMINUS);
          }
        case 108: break;
        case 94: 
          { return symbol(CONTINUE);
          }
        case 109: break;
        case 83: 
          { return symbol(STATIC);
          }
        case 110: break;
        case 39: 
          { return symbol(DO);
          }
        case 111: break;
        case 38: 
          { return symbol(IS);
          }
        case 112: break;
        case 51: 
          { return symbol(PLUSPLUS);
          }
        case 113: break;
        case 20: 
          { return symbol(LT);
          }
        case 114: break;
        case 90: 
          { return symbol(EXTENDS);
          }
        case 115: break;
        case 46: 
          { return symbol(ANDEQ);
          }
        case 116: break;
        case 87: 
          { return symbol(PUBLIC);
          }
        case 117: break;
        case 53: 
          { return symbol(MODEQ);
          }
        case 118: break;
        case 93: 
          { return symbol(ABSTRACT);
          }
        case 119: break;
        case 88: 
          { return symbol(BOOLEAN);
          }
        case 120: break;
        case 72: 
          { return symbol(THROW);
          }
        case 121: break;
        case 40: 
          { return symbol(EQEQ);
          }
        case 122: break;
        case 98: 
          { return symbol(IMPLEMENTS);
          }
        case 123: break;
        case 6: 
          { return symbol(NUMBER_LITERAL, new Double(yytext()));
          }
        case 124: break;
        case 64: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(true));
          }
        case 125: break;
        case 26: 
          { return symbol(OR);
          }
        case 126: break;
        case 27: 
          { return symbol(PLUS);
          }
        case 127: break;
        case 70: 
          { return symbol(PASS);
          }
        case 128: break;
        case 80: 
          { return symbol(NUMBER);
          }
        case 129: break;
        case 11: 
          { return symbol(RPAREN);
          }
        case 130: break;
        case 42: 
          { return symbol(RSHIFT);
          }
        case 131: break;
        case 78: 
          { return symbol(CLASS);
          }
        case 132: break;
        case 65: 
          { return symbol(THIS);
          }
        case 133: break;
        case 33: 
          { return symbol(MULTEQ);
          }
        case 134: break;
        case 92: 
          { return symbol(PRIVATE);
          }
        case 135: break;
        case 61: 
          { return symbol(URSHIFT);
          }
        case 136: break;
        case 89: 
          { return symbol(FINALLY);
          }
        case 137: break;
        case 71: 
          { return symbol(URSHIFTEQ);
          }
        case 138: break;
        case 57: 
          { return symbol(FOR);
          }
        case 139: break;
        case 55: 
          { return symbol(NEW);
          }
        case 140: break;
        case 32: 
          { return symbol(DIVEQ);
          }
        case 141: break;
        case 91: 
          { return symbol(DEFAULT);
          }
        case 142: break;
        case 23: 
          { return symbol(QUESTION);
          }
        case 143: break;
        case 3: 
          { return symbol(DIV);
          }
        case 144: break;
        case 37: 
          { return symbol(IF);
          }
        case 145: break;
        case 5: 
          { return symbol(IDENTIFIER, yytext());
          }
        case 146: break;
        case 54: 
          { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
          }
        case 147: break;
        case 52: 
          { return symbol(XOREQ);
          }
        case 148: break;
        case 84: 
          { return symbol(SWITCH);
          }
        case 149: break;
        case 62: 
          { return symbol(LSHIFTEQ);
          }
        case 150: break;
        case 29: 
          { return symbol(MOD);
          }
        case 151: break;
        case 10: 
          { return symbol(LPAREN);
          }
        case 152: break;
        case 44: 
          { return symbol(LSHIFT);
          }
        case 153: break;
        case 73: 
          { return symbol(BREAK);
          }
        case 154: break;
        case 22: 
          { return symbol(COMP);
          }
        case 155: break;
        case 63: 
          { return symbol(NULL_LITERAL);
          }
        case 156: break;
        case 35: 
          { return symbol(MINUSEQ);
          }
        case 157: break;
        case 66: 
          { return symbol(FROM);
          }
        case 158: break;
        case 56: 
          { return symbol(TRY);
          }
        case 159: break;
        case 1: 
          { throw new RuntimeException("Illegal character \""+yytext()+
                                                              "\" at line "+yyline+", column "+yycolumn);
          }
        case 160: break;
        case 48: 
          { return symbol(OREQ);
          }
        case 161: break;
        case 13: 
          { return symbol(RBRACK);
          }
        case 162: break;
        case 69: 
          { return symbol(ISNT);
          }
        case 163: break;
        case 16: 
          { return symbol(SEMICOLON);
          }
        case 164: break;
        case 86: 
          { return symbol(IMPORT);
          }
        case 165: break;
        case 76: 
          { return symbol(SUPER);
          }
        case 166: break;
        case 67: 
          { return symbol(CASE);
          }
        case 167: break;
        case 8: 
          { return symbol(MINUS);
          }
        case 168: break;
        case 7: 
          { return symbol(DOT);
          }
        case 169: break;
        case 60: 
          { return symbol(RSHIFTEQ);
          }
        case 170: break;
        case 97: 
          { return symbol(PROTECTED);
          }
        case 171: break;
        case 25: 
          { return symbol(AND);
          }
        case 172: break;
        case 96: 
          { return symbol(UNDEFINED_LITERAL);
          }
        case 173: break;
        case 24: 
          { return symbol(COLON);
          }
        case 174: break;
        case 43: 
          { return symbol(LTEQ);
          }
        case 175: break;
        case 75: 
          { return symbol(ARRAY);
          }
        case 176: break;
        case 21: 
          { return symbol(NOT);
          }
        case 177: break;
        case 82: 
          { return symbol(STRING);
          }
        case 178: break;
        case 31: 
          { yybegin(YYINITIAL); return symbol(STRING_LITERAL, string.toString());
          }
        case 179: break;
        case 15: 
          { return symbol(RBRACE);
          }
        case 180: break;
        case 4: 
          { return symbol(MULT);
          }
        case 181: break;
        case 2: 
          { /* ignore */
          }
        case 182: break;
        case 12: 
          { return symbol(LBRACK);
          }
        case 183: break;
        case 49: 
          { return symbol(OROR);
          }
        case 184: break;
        case 36: 
          { return symbol(AS);
          }
        case 185: break;
        case 30: 
          { string.append( yytext() );
          }
        case 186: break;
        case 95: 
          { return symbol(INTERFACE);
          }
        case 187: break;
        case 74: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(false));
          }
        case 188: break;
        case 58: 
          { return symbol(DEF);
          }
        case 189: break;
        case 47: 
          { return symbol(ANDAND);
          }
        case 190: break;
        case 79: 
          { return symbol(WHILE);
          }
        case 191: break;
        case 50: 
          { return symbol(PLUSEQ);
          }
        case 192: break;
        case 68: 
          { return symbol(ELSE);
          }
        case 193: break;
        case 77: 
          { return symbol(CATCH);
          }
        case 194: break;
        case 17: 
          { return symbol(COMMA);
          }
        case 195: break;
        case 81: 
          { return symbol(RETURN);
          }
        case 196: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface CrystalSymbol
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = CrystalSymbol.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          scanner = new Scanner( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
