
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 18 22:31:01 PDT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CrystalSymbol {
  /* terminals */
  public static final int AS = 21;
  public static final int IDENTIFIER = 92;
  public static final int ANDEQ = 83;
  public static final int GT = 62;
  public static final int IMPLEMENTS = 29;
  public static final int NEWLINE = 93;
  public static final int NOTEQ = 68;
  public static final int PLUSEQ = 78;
  public static final int PASS = 86;
  public static final int RBRACK = 9;
  public static final int CATCH = 47;
  public static final int COMMA = 13;
  public static final int RBRACE = 15;
  public static final int THROW = 45;
  public static final int RPAREN = 18;
  public static final int ISNT = 66;
  public static final int LBRACK = 8;
  public static final int LT = 61;
  public static final int ANDAND = 72;
  public static final int OROR = 73;
  public static final int LBRACE = 14;
  public static final int LPAREN = 17;
  public static final int XOREQ = 84;
  public static final int PROTECTED = 23;
  public static final int NOT = 55;
  public static final int DEF = 30;
  public static final int ARRAY = 2;
  public static final int OBJECT = 5;
  public static final int VAR = 7;
  public static final int URSHIFTEQ = 82;
  public static final int COMP = 54;
  public static final int EQ = 16;
  public static final int NUMBER_LITERAL = 87;
  public static final int UNDEFINED_LITERAL = 91;
  public static final int BOOLEAN_LITERAL = 88;
  public static final int MOD = 57;
  public static final int CLASS = 27;
  public static final int NUMBER = 4;
  public static final int SUPER = 32;
  public static final int ABSTRACT = 26;
  public static final int PLUS = 52;
  public static final int QUESTION = 74;
  public static final int WHILE = 40;
  public static final int EXTENDS = 28;
  public static final int INTERFACE = 33;
  public static final int BOOLEAN = 3;
  public static final int SWITCH = 36;
  public static final int DO = 39;
  public static final int FOR = 41;
  public static final int RSHIFTEQ = 81;
  public static final int DIV = 56;
  public static final int PUBLIC = 22;
  public static final int RETURN = 44;
  public static final int MULT = 12;
  public static final int ENDOFFILE = 94;
  public static final int ELSE = 35;
  public static final int TRY = 46;
  public static final int BREAK = 42;
  public static final int GTEQ = 64;
  public static final int DOT = 10;
  public static final int NULL_LITERAL = 90;
  public static final int STRING_LITERAL = 89;
  public static final int EQEQ = 67;
  public static final int EOF = 0;
  public static final int SEMICOLON = 11;
  public static final int THIS = 31;
  public static final int DEFAULT = 38;
  public static final int MULTEQ = 75;
  public static final int IMPORT = 20;
  public static final int IS = 65;
  public static final int MINUS = 53;
  public static final int LTEQ = 63;
  public static final int OR = 71;
  public static final int error = 1;
  public static final int URSHIFT = 60;
  public static final int DIVEQ = 76;
  public static final int LSHIFTEQ = 80;
  public static final int FINALLY = 48;
  public static final int CONTINUE = 43;
  public static final int IF = 34;
  public static final int MODEQ = 77;
  public static final int MINUSMINUS = 51;
  public static final int COLON = 19;
  public static final int OREQ = 85;
  public static final int CASE = 37;
  public static final int PLUSPLUS = 50;
  public static final int NEW = 49;
  public static final int RSHIFT = 59;
  public static final int STRING = 6;
  public static final int AND = 69;
  public static final int PRIVATE = 24;
  public static final int STATIC = 25;
  public static final int LSHIFT = 58;
  public static final int XOR = 70;
  public static final int MINUSEQ = 79;
}

