
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 09 17:55:00 PDT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CrystalSymbol {
  /* terminals */
  public static final int AS = 21;
  public static final int IDENTIFIER = 94;
  public static final int ANDEQ = 85;
  public static final int FROM = 22;
  public static final int GT = 64;
  public static final int IMPLEMENTS = 30;
  public static final int NOTEQ = 70;
  public static final int PLUSEQ = 80;
  public static final int PASS = 88;
  public static final int CONSTRUCTOR = 31;
  public static final int RBRACK = 9;
  public static final int CATCH = 49;
  public static final int COMMA = 13;
  public static final int RBRACE = 18;
  public static final int THROW = 47;
  public static final int RPAREN = 16;
  public static final int ISNT = 68;
  public static final int LBRACK = 8;
  public static final int LT = 63;
  public static final int ANDAND = 74;
  public static final int OROR = 75;
  public static final int LBRACE = 17;
  public static final int LPAREN = 15;
  public static final int XOREQ = 86;
  public static final int PROTECTED = 24;
  public static final int NOT = 57;
  public static final int DEF = 32;
  public static final int ARRAY = 2;
  public static final int OBJECT = 5;
  public static final int VAR = 7;
  public static final int URSHIFTEQ = 84;
  public static final int COMP = 56;
  public static final int EQ = 14;
  public static final int NUMBER_LITERAL = 89;
  public static final int UNDEFINED_LITERAL = 93;
  public static final int BOOLEAN_LITERAL = 90;
  public static final int MOD = 59;
  public static final int CLASS = 28;
  public static final int NUMBER = 4;
  public static final int SUPER = 34;
  public static final int ABSTRACT = 27;
  public static final int PLUS = 54;
  public static final int QUESTION = 76;
  public static final int WHILE = 42;
  public static final int EXTENDS = 29;
  public static final int INTERFACE = 35;
  public static final int BOOLEAN = 3;
  public static final int SWITCH = 38;
  public static final int DO = 41;
  public static final int FOR = 43;
  public static final int RSHIFTEQ = 83;
  public static final int DIV = 58;
  public static final int PUBLIC = 23;
  public static final int RETURN = 46;
  public static final int MULT = 12;
  public static final int ELSE = 37;
  public static final int TRY = 48;
  public static final int BREAK = 44;
  public static final int GTEQ = 66;
  public static final int DOT = 10;
  public static final int NULL_LITERAL = 92;
  public static final int STRING_LITERAL = 91;
  public static final int EQEQ = 69;
  public static final int EOF = 0;
  public static final int SEMICOLON = 11;
  public static final int THIS = 33;
  public static final int DEFAULT = 40;
  public static final int MULTEQ = 77;
  public static final int IMPORT = 20;
  public static final int IS = 67;
  public static final int MINUS = 55;
  public static final int LTEQ = 65;
  public static final int OR = 73;
  public static final int error = 1;
  public static final int URSHIFT = 62;
  public static final int DIVEQ = 78;
  public static final int LSHIFTEQ = 82;
  public static final int FINALLY = 50;
  public static final int CONTINUE = 45;
  public static final int IF = 36;
  public static final int MODEQ = 79;
  public static final int MINUSMINUS = 53;
  public static final int COLON = 19;
  public static final int OREQ = 87;
  public static final int CASE = 39;
  public static final int PLUSPLUS = 52;
  public static final int NEW = 51;
  public static final int RSHIFT = 61;
  public static final int STRING = 6;
  public static final int AND = 71;
  public static final int PRIVATE = 25;
  public static final int STATIC = 26;
  public static final int LSHIFT = 60;
  public static final int XOR = 72;
  public static final int MINUSEQ = 81;
}

